language: cpp

sudo: required

services:
- docker

script:
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker/
  - cp -r $HOME/.ccache ${HOME}/docker/ccache
  - export TRAVIS_REPO_SLUG=lammps/lammps
  - docker build -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/
                 ${TRAVIS_TAG:+-t ${TRAVIS_REPO_SLUG}:${TRAVIS_TAG}} &&
    rm -rf ${HOME}/.ccache &&
    CON=$(docker run -d ${TRAVIS_REPO_SLUG}:latest /bin/bash) &&
    docker cp ${CON}:/home/lammps/.ccache ${HOME}/

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master|patch_*) ]] && DEPLOY=yes
  - if [[ ${TRAVIS_BRANCH} = master ]]; then DOCKER_TAG=latest; else DOCKER_TAG="${TRAVIS_BRANCH}"; fi
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:latest";
    fi

cache:
  ccache: true

compiler:
  - gcc
